const bridge = window.AstrBotPluginPage;
const panels = [...document.querySelectorAll('[data-view-panel]')];
const links = [...document.querySelectorAll('[data-view]')];
let toastTimer;
function notify(message, error=false){const host=document.querySelector('#toast');host.innerHTML=`<div class="toast-message ${error?'error':''}" role="status">${message}</div>`;clearTimeout(toastTimer);toastTimer=setTimeout(()=>host.replaceChildren(),2600)}
function showView(name){const next=panels.some(panel=>panel.dataset.viewPanel===name)?name:'overview';panels.forEach(panel=>panel.classList.toggle('active',panel.dataset.viewPanel===next));document.querySelectorAll('.admin-nav-link').forEach(link=>link.classList.toggle('active',link.dataset.view===next));history.replaceState(null,'',`#${next}`);window.scrollTo({top:0,behavior:'smooth'});if(next==='overview') loadStats()}
async function apiGet(endpoint, params){if(!bridge?.apiGet) throw new Error('当前页面尚未连接 AstrBot Bridge');return bridge.apiGet(endpoint, params)}
async function apiPost(endpoint, body){if(!bridge?.apiPost) throw new Error('当前页面尚未连接 AstrBot Bridge');return bridge.apiPost(endpoint, body)}
async function loadSettings(){try{const settings=await apiGet('settings'); applySettings(settings)}catch(error){notify(`读取配置失败：${error.message}`,true)}}
function applySettings(settings){const map={proxy:'#proxy',timeout_seconds:'#timeout',default_count:'#count',cache_ttl_minutes:'#cache-ttl',max_file_size_mb:'#max-size',download_concurrency:'#concurrency'};Object.entries(map).forEach(([key,selector])=>{const el=document.querySelector(selector);if(el&&settings[key]!==undefined)el.value=settings[key]});document.querySelectorAll('[data-config-key]').forEach(el=>{const key=el.dataset.configKey;if(settings[key]!==undefined)el.checked=Boolean(settings[key])})}
async function saveSettings(){const payload={proxy:document.querySelector('#proxy')?.value||'',timeout_seconds:Number(document.querySelector('#timeout')?.value||20),default_count:Number(document.querySelector('#count')?.value||5),cache_ttl_minutes:Number(document.querySelector('#cache-ttl')?.value||30),max_file_size_mb:Number(document.querySelector('#max-size')?.value||12),download_concurrency:Number(document.querySelector('#concurrency')?.value||3)};document.querySelectorAll('[data-config-key]').forEach(el=>payload[el.dataset.configKey]=el.checked);try{await apiPost('settings/save',payload);document.querySelector('.last-saved')?.replaceChildren(document.createTextNode('最后保存：刚刚'));notify('设置已写入 AstrBot 插件配置')}catch(error){notify(`保存失败：${error.message}`,true)}}
async function loadStats(){try{const stats=await apiGet('stats');const values=document.querySelectorAll('.metric-card>strong');if(values[3]&&stats.requests_today!==undefined)values[3].textContent=stats.requests_today}catch(error){/* overview may be opened outside AstrBot */}}
links.forEach(link=>link.addEventListener('click',event=>{event.preventDefault();showView(link.dataset.view)}));window.addEventListener('hashchange',()=>showView(location.hash.slice(1)||'overview'));document.querySelector('#help-button')?.addEventListener('click',()=>showView('guide'));
document.querySelectorAll('.save-button, #save-overview').forEach(button=>button.addEventListener('click',saveSettings));
document.querySelector('#test-connection')?.addEventListener('click',async()=>{const button=document.querySelector('#test-connection');button.disabled=true;button.textContent='验证中…';try{const result=await apiPost('connection/test',{});notify(result.message||'Pixiv 连接测试通过')}catch(error){notify(`连接失败：${error.message}`,true)}finally{button.disabled=false;button.textContent='测试连接'}});
document.querySelector('#clear-token')?.addEventListener('click',async()=>{try{await apiPost('settings/save',{refresh_token:''});notify('Refresh Token 已清除')}catch(error){notify(`清除失败：${error.message}`,true)}});
document.querySelector('#run-diagnostics')?.addEventListener('click',async()=>{const button=document.querySelector('#run-diagnostics');button.disabled=true;button.textContent='检查中…';try{const result=await apiPost('diagnostics/run',{});notify(result.ok?'诊断通过':'诊断完成，请检查配置')}catch(error){notify(`诊断失败：${error.message}`,true)}finally{button.disabled=false;button.textContent='运行诊断'}});
document.querySelector('#refresh-activity')?.addEventListener('click',()=>loadStats().then(()=>notify('活动记录已刷新')));document.querySelector('#clear-cache')?.addEventListener('click',async()=>{try{await apiPost('cache/clear',{});notify('缓存已清理')}catch(error){notify(`清理失败：${error.message}`,true)}});document.querySelector('#clear-temp')?.addEventListener('click',async()=>{try{await apiPost('cache/clear',{temporary:true});notify('临时文件清理请求已提交')}catch(error){notify(`清理失败：${error.message}`,true)}});document.querySelector('#copy-diagnostics')?.addEventListener('click',()=>notify('请使用 AstrBot Bridge 集成后复制脱敏摘要'));
document.querySelectorAll('.copy-prompt').forEach(button=>button.addEventListener('click',async()=>{try{await navigator.clipboard?.writeText(button.dataset.copy);notify(`已复制：${button.dataset.copy}`)}catch{notify(`示例：${button.dataset.copy}`)}}));
(async()=>{try{await bridge?.ready?.();await loadSettings();await loadStats()}catch(error){notify(`Bridge 尚未就绪：${error.message}`,true)}showView(location.hash.slice(1)||'overview')})();

